### ISSUE TITLE
Add local file path to download

### ISSUE THREAD

**Issue by carissableker** [EBI-BioModels/biomodels-resftful-api-client#1]
Hi BioModels team, 

In the in the download function would it be possible to add an argument for the target file path (`local_file`)? 

https://github.com/EBI-BioModels/biomodels-resftful-api-client/blob/5192115e68b708daecfa450c389e90b34bb5d1c5/src/biomodels_restful_api_client/services.py#L39-L52

Currently it will just download the file to the remote `filename` into whatever directory the code happens to be running from. It does return the file path, so that I could move it to a proper location, but that does not seem very efficient or safe. 

Another issue in the current implementation is, if `filename` is not passed, `local_file` is also `None`, and will crash when saving. 

Something along the following will handle both issues: 

```python

# GET /model/download/{model_id}
def download(model_id, filename=None, local_file=None):
    download_url = API_URL + "/model/download/" + model_id
    
    if filename is not None:
        response = requests.get(download_url + "?filename=" + filename)
    else:
        response = requests.get(download_url)


    # Determine local file name, if not given
    if local_file is None:
        if filename is not None:
            local_file = filename
        else:
            # make up a name for the entire archive
            local_file = f"{model_id}.omex"

    # Save the file data to the local file
    with open(local_file, 'wb') as file:
        file.write(response.content)

    return os.path.abspath(local_file)
```

**Comment by ntung** [comment]
Hi @carissableker ,

Thank you for raising the issue!

I am sorry for the delayed response. Seemingly, I will not be notified once a new issue is created.

We will look into the issue and fix it in the next interation asap.

Regards,
Tung

**Comment by ntung** [comment]
@carissableker 
Please upgrade your Python environment in order to get the latest version of our library - v0.1.3
Cheers,
Tung
